### ISSUE TITLE
Character entity reference

### ISSUE THREAD

**Issue by jim-rosales** [xiaobin900114/DasmotoArt#2]
In HTML the `&` is a reserved character which is why currently it is highlighted in red by GitHub. It's a reserved character since it is used to add special characters via an [entity reference](https://www.codecademy.com/articles/accessibility).

For example, in this case, since the ampersand is a reserved character we need to add it via its entity reference. To do this all that is required here is to replace `&` with `&amp;` 

https://github.com/xiaobin900114/DasmotoArt/blob/2daf6b264f2af7ef43c8b4faba8d70adb5a62956/DasmotoArt/index.html#L5

**Comment by xiaobin900114** [comment]
Got it! Thanks!
