### ISSUE TITLE
Em Use

### ISSUE THREAD

**Issue by jim-rosales** [xiaobin900114/DasmotoArt#3]
NIce job here using a class to apply the desired styles to all your classes! 

Considering you're overriding the default styling that comes with the em tag to get the bold non-italic blue font here are a couple alternatives that achieve the same results with less CSS.

Option 1: Making use of the [span](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/span) element
```HTML
<p>
Imported paint from Finland. Over 256 colors available in-store, varying in quantity (1 oz. to 8 oz.). Clean Finnish paint microbinds to canvas, increasing the finish and longevity of any artwork. <span class="price">Starting at $5.00 / tube.</span>
</p>
```

```CSS
.price {
  font-weight: bold;
  color: blue;
}
```

Option 2: Making use of the [strong](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strong) element
```HTML
<p>
Imported paint from Finland. Over 256 colors available in-store, varying in quantity (1 oz. to 8 oz.). Clean Finnish paint microbinds to canvas, increasing the finish and longevity of any artwork. <strong class="price">Starting at $5.00 / tube.</strong>
</p>
```

```CSS
.price {
  color: blue;
}
```

https://github.com/xiaobin900114/DasmotoArt/blob/2daf6b264f2af7ef43c8b4faba8d70adb5a62956/DasmotoArt/index.html#L32

**Comment by xiaobin900114** [comment]
I totally forgot the "span" element. I just want to add an inline style element, which only "em" and "strong" came into mind. Now I found "span" was the one I was looking for. Thanks!
