### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jim-rosales** [xiaobin900114/DasmotoArt#4]
Grade: Meets Expectations

Summary:
Congrats on finishing the Dasmoto project! Overall you did an excellent job implementing all the requirements form the specification sheet. You did an excellent job making use of divs and classes to structure your HTML file. Apart from this, you did an excellent job applying your CSS styles as I as you make great use of universal styles to eliminate duplicate code in your stylesheet. 

One thing to note for future projects is comments as I didn't see you make use of then in this project. Comments help improve the readability of projects especially as they grow in complexity which is why it's always a great idea to add them. Apart from this, I would also suggest you read over this [article](https://www.granneman.com/webdev/coding/formatting-and-indenting-your-html/) that goes in depth to the best practices when it comes to formatting HTML file. 

You can also look at this [HTML](https://gist.github.com/jim-rosales/c1446e66054c97071406610be771fa79) and [CSS](https://gist.github.com/jim-rosales/2f5cfda50385ffddc1225f0e8a9f4807) solution for the project that incorporates the best practices mentioned above so you can compare and contrast your implementations with the solutions. 

 If you'd like to learn about CSS on your own, I would suggest you read over [variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables), the [transition](https://developer.mozilla.org/en-US/docs/Web/CSS/transition) property and the pseudo-classes [hover](https://developer.mozilla.org/en-US/docs/Web/CSS/:hover) and [active](https://developer.mozilla.org/en-US/docs/Web/CSS/:active). 

This [codepen](https://codepen.io/honglio/pen/FKyxG) showcases a couple uses of some of the CSS tools mentioned above.

**Comment by xiaobin900114** [comment]
Thanks so much for review my project and leave this comment. I found your suggestion on further reading is very helpful. I really appreciate it.
